/**
 * Every string the billing wizard renders.
 *
 * Kept beside the slice that owns it rather than in `messages.ts`, so two
 * slices of the module never edit the same catalogue. The host merges each
 * bundle recursively, so these land under the same `tasks_projects` namespace
 * as the rest.
 */
export const billingMessages = {
  en: {
    tasks_projects: {
      billing: {
        title: 'Invoice time',
        subtitle: 'Turn unbilled hours into a draft invoice.',
        invoice_time: 'Invoice time',
        unbilled: 'Unbilled',
        view_unbilled: 'Invoice this time',
        steps: {
          customer: 'Customer',
          entries: 'Entries',
          preview: 'Preview',
          create: 'Create',
        },
        back: 'Back',
        next: 'Continue',
        start_over: 'Start over',
        customer: {
          title: 'Who are you invoicing?',
          description: 'Customers with billable time that has not reached an invoice yet.',
          entries: '{count} entries',
          empty_title: 'Nothing to invoice',
          empty_description:
            'Billable time appears here once it has been logged against a task that belongs to a customer.',
          load_failed: 'Unable to load the customers with unbilled time.',
          names_failed: 'Unable to load the customer names; ids are shown instead.',
          unnamed: 'Customer #{id}',
          from: 'From',
          to: 'To',
          clear_range: 'Clear dates',
        },
        entries: {
          title: 'Which time goes on the invoice?',
          grouping: 'Group lines by',
          group_by: {
            task: 'Task',
            project: 'Project',
            member: 'Member',
            summary: 'One summary line',
          },
          select_all: 'Select all',
          selected: '{count} of {total} entries selected',
          selected_total: 'Selected: {hours}',
          no_description: 'No description',
          columns: {
            date: 'Date',
            task: 'Task',
            project: 'Project',
            member: 'Member',
            duration: 'Duration',
            amount: 'Amount',
          },
          empty_title: 'No unbilled time',
          empty_description: 'This customer has nothing waiting to be invoiced in this range.',
          load_failed: 'Unable to load the unbilled time.',
          none_selected: 'Select at least one entry.',
        },
        preview: {
          title: 'Check the invoice',
          lines: 'Invoice lines',
          columns: {
            description: 'Description',
            quantity: 'Hours',
            price: 'Rate',
            total: 'Amount',
          },
          sub_total: 'Subtotal',
          total: 'Total',
          invoice_date: 'Invoice date',
          due_date: 'Due date',
          invoice_number: 'Invoice number',
          invoice_number_auto: 'Generated by the company number format.',
          template: 'Template',
          exchange_rate: 'Exchange rate',
          exchange_rate_help: '1 {currency} in the company currency.',
          prepare_failed: 'Unable to prepare the invoice.',
          templates_failed: 'Unable to load the invoice templates.',
          number_failed: 'Unable to read the next invoice number. Type one in.',
          rate_failed: 'Unable to read the exchange rate. Type one in.',
          create: 'Create invoice',
          invalid: 'The invoice was refused. Fix the fields below and try again.',
        },
        create: {
          creating: 'Creating the invoice',
          stamping: 'Marking the time as invoiced',
          created_title: 'Invoice {number} created',
          created_description: '{count} entries were marked as invoiced.',
          view_invoice: 'Open the invoice',
          invoice_more: 'Invoice more time',
          failed: 'Unable to create the invoice.',
          stamp_failed_title: 'The invoice was created, but the time is not marked yet',
          stamp_failed_description:
            'Invoice {number} exists. The time entries still count as unbilled until they are stamped, which is safe to run again.',
          retry_stamp: 'Retry stamping',
          stamped: 'The time entries were marked as invoiced.',
        },
      },
    },
  },
}
